-- ════════════════════════════════════════════════════════════════════════════
--  Tendo — schéma Supabase
--
--  À exécuter une fois, en entier, dans l'éditeur SQL de Supabase.
--  Tableau de bord > SQL Editor > New query > coller > Run.
--
--  Principe de sécurité : chaque table active Row Level Security et chaque
--  politique filtre sur auth.uid(). Un utilisateur ne peut voir et écrire que
--  ses propres lignes, même si la clé publique de l'app fuite — elle est faite
--  pour être publique. La seule exception est strava_tokens, qui n'a AUCUNE
--  politique : la table est donc totalement inaccessible depuis le navigateur.
--  Seules les fonctions Netlify, qui utilisent la clé de service, y touchent.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── Profil ─────────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id                  uuid primary key references auth.users on delete cascade,
  display_name        text,
  -- Allure marathon OBJECTIF en secondes par kilomètre. Ancre les six zones.
  -- 277 = 4:37/km = 3 h 15.
  marathon_pace_s     integer not null default 277,
  -- Allure marathon projetée par le dernier test. 289 = 4:49/km = 3 h 23.
  fitness_pace_s      integer not null default 289,
  -- Dernier test de 3 km, en secondes. 722 = 12:02.
  test_3k_s           integer,
  test_3k_date        date,
  -- Fréquence cardiaque maximale mesurée. 181 pour Mathieu, et non les 193
  -- que Strava suppose : voir la section « Zones cardiaques » du CLAUDE.md.
  hr_max              integer not null default 181,
  goal_label          text not null default '3 h 15',
  race_date           date not null default '2027-04-11',
  plan_start          date not null default '2026-08-10',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ─── Journal quotidien (le carnet de suivi tendon) ──────────────────────────
create table if not exists public.daily_logs (
  user_id       uuid not null references auth.users on delete cascade,
  day           date not null,
  -- Les trois mesures de douleur, 0 à 10. La raideur au réveil est le marqueur
  -- de référence, la douleur du soir est celle qui parle le plus chez Mathieu.
  pain_wake     numeric(3,1) check (pain_wake between 0 and 10),
  pain_effort   numeric(3,1) check (pain_effort between 0 and 10),
  pain_evening  numeric(3,1) check (pain_evening between 0 and 10),
  -- Gestes protecteurs : ils font BAISSER l'indice de charge du tendon.
  eccentric     boolean not null default false,
  icing         boolean not null default false,
  jumps         boolean not null default false,
  stretching    boolean not null default false,
  hydration_l   numeric(3,1),
  mood          text,
  note          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (user_id, day)
);
create index if not exists daily_logs_user_day_idx on public.daily_logs (user_id, day desc);

-- ─── Ressenti après chaque séance ───────────────────────────────────────────
create table if not exists public.session_feedback (
  user_id       uuid not null references auth.users on delete cascade,
  -- Repère de la séance dans le plan : semaine 1-35, jour 0-6, index dans la journée.
  week          smallint not null check (week between 1 and 60),
  day_index     smallint not null check (day_index between 0 and 6),
  slot          smallint not null default 0,
  day           date not null,
  session_type  text not null,
  -- Douleur au tendon pendant et juste après la séance, 0 à 10.
  pain          numeric(3,1) not null check (pain between 0 and 10),
  -- Effort perçu, échelle RPE 0 à 10.
  rpe           smallint not null check (rpe between 0 and 10),
  distance_km   numeric(5,2),
  note          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (user_id, week, day_index, slot)
);
create index if not exists session_feedback_user_day_idx
  on public.session_feedback (user_id, day desc);

-- ─── Activités importées (Strava, ou saisie manuelle) ───────────────────────
create table if not exists public.activities (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users on delete cascade,
  source           text not null default 'strava',
  external_id      text,
  day              date not null,
  started_at       timestamptz,
  sport            text not null,
  name             text,
  distance_m       numeric(10,1) not null default 0,
  moving_s         integer not null default 0,
  elapsed_s        integer,
  elevation_m      numeric(7,1),
  avg_hr           numeric(5,1),
  max_hr           numeric(5,1),
  avg_watts        numeric(6,1),
  relative_effort  integer,
  created_at       timestamptz not null default now(),
  unique (user_id, source, external_id)
);
create index if not exists activities_user_day_idx on public.activities (user_id, day desc);

-- ─── Modifications manuelles du plan ────────────────────────────────────────
-- Le plan des 35 semaines vit dans le code (src/data/plan.json) : c'est une
-- donnée de référence, pas une donnée utilisateur. Cette table ne stocke que
-- les écarts volontaires, pour ne pas dupliquer 315 séances par utilisateur.
create table if not exists public.plan_overrides (
  user_id     uuid not null references auth.users on delete cascade,
  week        smallint not null,
  day_index   smallint not null,
  slot        smallint not null default 0,
  patch       jsonb not null,
  reason      text,
  created_at  timestamptz not null default now(),
  primary key (user_id, week, day_index, slot)
);

-- ─── Jetons Strava — jamais accessibles depuis le navigateur ────────────────
create table if not exists public.strava_tokens (
  user_id       uuid primary key references auth.users on delete cascade,
  athlete_id    bigint,
  access_token  text not null,
  refresh_token text not null,
  expires_at    timestamptz not null,
  scope         text,
  last_sync_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ════════════════════════════════════════════════════════════════════════════
--  Row Level Security
-- ════════════════════════════════════════════════════════════════════════════
alter table public.profiles          enable row level security;
alter table public.daily_logs        enable row level security;
alter table public.session_feedback  enable row level security;
alter table public.activities        enable row level security;
alter table public.plan_overrides    enable row level security;
-- RLS activé SANS aucune politique : personne n'y accède avec la clé publique.
alter table public.strava_tokens     enable row level security;

-- profiles : chacun lit et modifie sa ligne.
drop policy if exists "profil visible par son propriétaire" on public.profiles;
create policy "profil visible par son propriétaire"
  on public.profiles for select using (auth.uid() = id);
drop policy if exists "profil modifiable par son propriétaire" on public.profiles;
create policy "profil modifiable par son propriétaire"
  on public.profiles for update using (auth.uid() = id);
drop policy if exists "profil créable par son propriétaire" on public.profiles;
create policy "profil créable par son propriétaire"
  on public.profiles for insert with check (auth.uid() = id);

-- Les quatre tables de données suivent exactement le même patron :
-- on ne lit, écrit, modifie et supprime que ses propres lignes.

-- daily_logs
drop policy if exists "daily_logs lecture" on public.daily_logs;
create policy "daily_logs lecture"
  on public.daily_logs for select using (auth.uid() = user_id);
drop policy if exists "daily_logs insertion" on public.daily_logs;
create policy "daily_logs insertion"
  on public.daily_logs for insert with check (auth.uid() = user_id);
drop policy if exists "daily_logs mise a jour" on public.daily_logs;
create policy "daily_logs mise a jour"
  on public.daily_logs for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "daily_logs suppression" on public.daily_logs;
create policy "daily_logs suppression"
  on public.daily_logs for delete using (auth.uid() = user_id);

-- session_feedback
drop policy if exists "session_feedback lecture" on public.session_feedback;
create policy "session_feedback lecture"
  on public.session_feedback for select using (auth.uid() = user_id);
drop policy if exists "session_feedback insertion" on public.session_feedback;
create policy "session_feedback insertion"
  on public.session_feedback for insert with check (auth.uid() = user_id);
drop policy if exists "session_feedback mise a jour" on public.session_feedback;
create policy "session_feedback mise a jour"
  on public.session_feedback for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "session_feedback suppression" on public.session_feedback;
create policy "session_feedback suppression"
  on public.session_feedback for delete using (auth.uid() = user_id);

-- activities
drop policy if exists "activities lecture" on public.activities;
create policy "activities lecture"
  on public.activities for select using (auth.uid() = user_id);
drop policy if exists "activities insertion" on public.activities;
create policy "activities insertion"
  on public.activities for insert with check (auth.uid() = user_id);
drop policy if exists "activities mise a jour" on public.activities;
create policy "activities mise a jour"
  on public.activities for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "activities suppression" on public.activities;
create policy "activities suppression"
  on public.activities for delete using (auth.uid() = user_id);

-- plan_overrides
drop policy if exists "plan_overrides lecture" on public.plan_overrides;
create policy "plan_overrides lecture"
  on public.plan_overrides for select using (auth.uid() = user_id);
drop policy if exists "plan_overrides insertion" on public.plan_overrides;
create policy "plan_overrides insertion"
  on public.plan_overrides for insert with check (auth.uid() = user_id);
drop policy if exists "plan_overrides mise a jour" on public.plan_overrides;
create policy "plan_overrides mise a jour"
  on public.plan_overrides for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "plan_overrides suppression" on public.plan_overrides;
create policy "plan_overrides suppression"
  on public.plan_overrides for delete using (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════════════════════
--  Automatismes
-- ════════════════════════════════════════════════════════════════════════════

-- Un profil est créé automatiquement à la première connexion.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- updated_at tenu à jour tout seul.
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists touch_profiles on public.profiles;
create trigger touch_profiles before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_daily_logs on public.daily_logs;
create trigger touch_daily_logs before update on public.daily_logs
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_session_feedback on public.session_feedback;
create trigger touch_session_feedback before update on public.session_feedback
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_strava_tokens on public.strava_tokens;
create trigger touch_strava_tokens before update on public.strava_tokens
  for each row execute function public.touch_updated_at();

-- ════════════════════════════════════════════════════════════════════════════
--  Vue de commodité : la charge tendineuse par jour, calculée côté base.
--
--  L'app calcule déjà l'indice en TypeScript (src/lib/tendonIndex.ts), ce qui
--  lui permet de fonctionner hors ligne. Cette vue sert aux vérifications et à
--  d'éventuelles tâches planifiées côté serveur — les deux calculs doivent
--  donner le même résultat, les coûts sont ceux de KM_COST et MIN_COST.
-- ════════════════════════════════════════════════════════════════════════════
create or replace view public.daily_tendon_load as
select
  user_id,
  day,
  round(sum(
    case
      when sport = 'Run' then
        (distance_m / 1000.0) * case
          when name ~* 'fractionn|x800|x400|x200|test' then 0.45 * 2.1 + 0.55 * 1.0
          when name ~* 'seuil|tempo'                   then 0.45 * 1.6 + 0.55 * 1.0
          when distance_m >= 18000                     then 1.15
          else 1.0
        end
      when sport = 'Ride'   then (moving_s / 60.0) * 0.10
      when sport = 'Weight' then (moving_s / 60.0)
                                 * case when name ~* 'jambe|bas|bulgare|trx' then 0.25 else 0.0 end
      when sport = 'Hike'   then (moving_s / 60.0) * 0.05
      else 0
    end
  )::numeric, 2) as load_km_eq
from public.activities
group by user_id, day;

comment on view public.daily_tendon_load is
  'Charge tendineuse quotidienne en kilomètres-équivalents. Doit rester alignée sur KM_COST et MIN_COST dans src/lib/tendonIndex.ts.';
